server:
  ip: "0.0.0.0"
  port: 2303

reboot:
  base_time: "00:00"
  interval_minutes: 240

locale: "en_UK"  # Switch to "en_UK" for British English

logging:
  enabled: true
  file: "logs/monitor.log"

output:
  to_console: true
  to_file: true
  to_discord: false
  file_path: "output/last_run.txt"
  show_removed_mods: true
  silent_on_no_changes: false
  show_island: true
  show_platform: true
  show_dedicated: true
  show_mod_count: true
  show_next_reboot: true

mod_checking_enabled: true
mod_check_mode: async  # serial | threaded | async

steam:
  api_key: "YOUR_STEAM_API_KEY"

discord:
  enabled: false
  token: "YOUR_DISCORD_BOT_TOKEN"
  channel_id: 123456789012345678
