# DayZ Server Monitor Configuration

server:
  ip: "127.0.0.1"
  port: 2302

reboot:
  base_time: "01:00"
  interval_minutes: 180

locale: "en_GB"

logging:
  enabled: true
  level: DEBUG
  log_dir: logs
  files:
    debug: debug.log
    info: info.log
    error: error.log
    critical: critical.log

output:
  to_console: true
  to_file: true
  to_discord: true
  file_path: output/last_run.txt
  show_removed_mods: true
  silent_on_no_changes: false
  show_island: true
  show_platform: true
  show_dedicated: true
  show_mod_count: true
  show_next_reboot: true

mod_checking_enabled: true
mod_check_mode: async  # Options: async, threaded, serial

threaded_mode:
  max_workers: 10

steam:
  api_key: ""  # Optional: used if you want authenticated requests

discord:
  enabled: true
  webhook_url: https://discord.com/api/webhooks/<some really stupidly long hash>
